### To-Do 조회
GET http://localhost:18080/api/todo/list?parameter=  HTTP/1.1
content-type: application/json



### 삭제
DELETE http://localhost:18080/api/todo/date/del?due_date=2025-03-05 HTTP/1.1
Content-Type: application/json




### 추가
POST http://localhost:18080/api/todo/add HTTP/1.1
content-type: application/json

{
    "title":"test",
    "status" : "",
    "due_month" : "",
    "due_date":"2025-03-15"
};




### 할 일 수정
PUT  http://localhost:18080/api/todo/update HTTP/1.1
content-type: application/json

{
   "id": 3,
    "title": "React 학231231습"
}



### 상태 수정
PUT  http://localhost:18080/api/todo/update/status HTTP/1.1
content-type: application/json

{
   "id": 15
}



###  스케줄 강제 실행
GET http://localhost:18080/api/todo/scheduled HTTP/1.1
content-type: application/json

{
}

### 이메일 전송
POST  http://localhost:18080/api/email/send HTTP/1.1
content-type: application/json

{
  "host": "smtp.naver.com",
  "port": 587,
  "username": "",
  "password": "",
  "to": "",
  "subject": "Test Email",
  "text": ["This is a test email body"]
}
